# Customer Sales Insights Analysis  
## Retail Customer Segmentation & Purchase Behaviour Analytics

This notebook focuses on analysing the final cleaned and merged retail dataset. The goal is to identify customer segment patterns, product performance, pack-size preferences, and sales behaviour using Pandas and NumPy.

The analysis in this notebook provides initial business insights before moving into SQL analysis and Power BI dashboard development.

In [1]:
# importing numpy library

import numpy as np

In [2]:
# importing pandas library

import pandas as pd

In [3]:
# loading merged dataset 

final_df = pd.read_csv(
    r"..data/Processed_data/final_customer_sales_data.csv"
)

final_df.head()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PACK_SIZE_(g),PROD_QTY,TOT_SALES,LIFESTAGE,PREMIUM_CUSTOMER
0,2018-10-17,1,1000,1,5,Natural Chip Compny SeaSalt,175,2,6.0,YOUNG SINGLES/COUPLES,Premium
1,2019-05-14,1,1307,348,66,CCs Nacho Cheese,175,3,6.3,MIDAGE SINGLES/COUPLES,Budget
2,2019-05-20,1,1343,383,61,Smiths Crinkle Cut Chips Chicken,170,2,2.9,MIDAGE SINGLES/COUPLES,Budget
3,2018-08-17,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion,175,5,15.0,MIDAGE SINGLES/COUPLES,Budget
4,2018-08-18,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili,150,3,13.8,MIDAGE SINGLES/COUPLES,Budget

In [5]:
# checking shape of the data 

final_df.shape

(264833, 11)

In [6]:
# a statistical summary of this data

final_df.describe()

,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PACK_SIZE_(g),PROD_QTY,TOT_SALES
count,264833.000000,2.648330e+05,2.648330e+05,264833.000000,264833.000000,264833.000000,264833.000000
mean,135.079529,1.355489e+05,1.351577e+05,56.583598,182.425540,1.905812,7.299351
std,76.784189,8.058003e+04,7.813305e+04,32.826498,64.325268,0.343437,2.527244
min,1.000000,1.000000e+03,1.000000e+00,1.000000,70.000000,1.000000,1.500000
25%,70.000000,7.002100e+04,6.760000e+04,28.000000,150.000000,2.000000,5.400000
50%,130.000000,1.303570e+05,1.351370e+05,56.000000,170.000000,2.000000,7.400000
75%,203.000000,2.030940e+05,2.027000e+05,85.000000,175.000000,2.000000,9.200000
max,272.000000,2.373711e+06,2.415841e+06,114.000000,380.000000,5.000000,29.500000

In [8]:
# 1. Sales by lifestage

revenue_by_lifestage = final_df.groupby("LIFESTAGE")["TOT_SALES"].sum().sort_values(ascending=False)
print(revenue_by_lifestage)

LIFESTAGE
OLDER SINGLES/COUPLES     402420.75
RETIREES                  366470.90
OLDER FAMILIES            352467.20
YOUNG FAMILIES            316160.10
YOUNG SINGLES/COUPLES     260405.30
MIDAGE SINGLES/COUPLES    184751.30
NEW FAMILIES               50433.45
Name: TOT_SALES, dtype: float64

It shows that older singles/ couples are generating the highest revenue while new families are generating lowest revenue

In [14]:
# 2. which product generated highest revenue and least revenue 

prod_revenue = final_df.groupby("PROD_NAME")["TOT_SALES"].sum().sort_values(ascending=False)
print("top 3 :\n",prod_revenue.head(3))
print("bottom 3 :\n",prod_revenue.tail(3))

top 3 :
 PROD_NAME
Dorito Corn Chp     Supreme            39052.0
Smiths Crnkle Chip  Orgnl Big Bag      36367.6
Smiths Crinkle Chips Salt & Vinegar    34804.2
Name: TOT_SALES, dtype: float64
bottom 3 :
 PROD_NAME
WW Crinkle Cut      Original    4532.2
Woolworths Mild     Salsa       4234.5
Woolworths Medium   Salsa       4050.0
Name: TOT_SALES, dtype: float64

Dorito Corn Chp Supreme generated highest revenue while Woolworths Medium Salsa generated least revenue

In [15]:
# 3. which product was highly consumed and least consumed

prod_consumed = final_df.groupby("PROD_NAME")["PROD_QTY"].sum().sort_values(ascending=False)
print("top 3 :\n",prod_consumed.head(3))
print("bottom 3 :\n",prod_consumed.tail(3))

top 3 :
 PROD_NAME
Kettle Mozzarella   Basil & Pesto      6381
Kettle Tortilla ChpsHny&Jlpno Chili    6309
Cobs Popd Sea Salt  Chips              6277
Name: PROD_QTY, dtype: int64
bottom 3 :
 PROD_NAME
NCC Sour Cream &    Garden Chives    2682
WW Crinkle Cut      Original         2666
French Fries Potato Chips            2643
Name: PROD_QTY, dtype: int64

Kettle Mozzarella Basil & Pesto was highly consumed and French Fries Potato Chips was least consumed

In [20]:
# changing dataype of date 

final_df["DATE"] = pd.to_datetime(final_df["DATE"])

# checking type
final_df.dtypes

DATE                datetime64[ns]
STORE_NBR                    int64
LYLTY_CARD_NBR               int64
TXN_ID                       int64
PROD_NBR                     int64
PROD_NAME                   object
PACK_SIZE_(g)                int64
PROD_QTY                     int64
TOT_SALES                  float64
LIFESTAGE                   object
PREMIUM_CUSTOMER            object
dtype: object

In [23]:
# 4. which month generated highest sales

m_sales = final_df.groupby(pd.Grouper(key="DATE",freq="ME"))["TOT_SALES"].sum().reset_index(name="Total sales").sort_values("Total sales",ascending=False)
m_sales["DATE"] = m_sales["DATE"].dt.strftime("%B %Y")
print(m_sales)

              DATE  Total sales
5    December 2018    167913.40
8       March 2019    166265.20
0        July 2018    165275.30
3     October 2018    164409.70
6     January 2019    162642.30
11       June 2019    160538.60
2   September 2018    160522.00
4    November 2018    160233.70
9       April 2019    159845.10
1      August 2018    158081.05
10        May 2019    156717.65
7    February 2019    150665.00

December 2018 generated the highest revenue while February 2019 generated lowest revenue

In [16]:
# 5. finding high value customers

hv_customers = final_df.groupby("LYLTY_CARD_NBR")["TOT_SALES"].sum().sort_values( ascending = False )
print(hv_customers.head(5))

LYLTY_CARD_NBR
230078    138.6
63197     132.8
259009    127.2
162039    126.8
58361     124.8
Name: TOT_SALES, dtype: float64

High-value customers were identified by grouping transactions by `LYLTY_CARD_NBR` and calculating total customer spend. Customers with the highest total spend represent the most valuable loyalty customers in the dataset.

In [9]:
# 6. categorising dataset based on sales 

final_df["Sales_Category"] = np.where(
    final_df["TOT_SALES"] >= final_df["TOT_SALES"].median(),
    "High Sale",
    "Low Sale"
)

final_df

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PACK_SIZE_(g),PROD_QTY,TOT_SALES,LIFESTAGE,PREMIUM_CUSTOMER,Sales_Category
0,2018-10-17,1,1000,1,5,Natural Chip Compny SeaSalt,175,2,6.0,YOUNG SINGLES/COUPLES,Premium,Low Sale
1,2019-05-14,1,1307,348,66,CCs Nacho Cheese,175,3,6.3,MIDAGE SINGLES/COUPLES,Budget,Low Sale
2,2019-05-20,1,1343,383,61,Smiths Crinkle Cut Chips Chicken,170,2,2.9,MIDAGE SINGLES/COUPLES,Budget,Low Sale
3,2018-08-17,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion,175,5,15.0,MIDAGE SINGLES/COUPLES,Budget,High Sale
4,2018-08-18,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili,150,3,13.8,MIDAGE SINGLES/COUPLES,Budget,High Sale
...,...,...,...,...,...,...,...,...,...,...,...,...
264828,2019-03-09,272,272319,270088,89,Kettle Sweet Chilli And Sour Cream,175,2,10.8,YOUNG SINGLES/COUPLES,Premium,High Sale
264829,2018-08-13,272,272358,270154,74,Tostitos Splash Of Lime,175,1,4.4,YOUNG SINGLES/COUPLES,Premium,Low Sale
264830,2018-11-06,272,272379,270187,51,Doritos Mexicana,170,2,8.8,YOUNG SINGLES/COUPLES,Premium,High Sale
264831,2018-12-27,272,272379,270188,42,Doritos Corn Chip Mexican Jalapeno,150,2,7.8,YOUNG SINGLES/COUPLES,Premium,High Sale
264832,2018-09-22,272,272380,270189,74,Tostitos Splash Of Lime,175,2,8.8,YOUNG SINGLES/COUPLES,Premium,High Sale

In [30]:
# 7. categorising products based on their pack size

final_df["PACK_CATG"] = np.select  (
    [
        final_df["PACK_SIZE_(g)"] <= 150 ,
        final_df["PACK_SIZE_(g)"].between(160,200),
        final_df["PACK_SIZE_(g)"] > 200
    ],
    [
        "Small pack",
        "Medium pack",
        "Large pack"
    ],
    default = "unknown"
)

final_df

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PACK_SIZE_(g),PROD_QTY,TOT_SALES,LIFESTAGE,PREMIUM_CUSTOMER,Sales_Category,PACK_CATG
0,2018-10-17,1,1000,1,5,Natural Chip Compny SeaSalt,175,2,6.0,YOUNG SINGLES/COUPLES,Premium,Low Sale,Medium pack
1,2019-05-14,1,1307,348,66,CCs Nacho Cheese,175,3,6.3,MIDAGE SINGLES/COUPLES,Budget,Low Sale,Medium pack
2,2019-05-20,1,1343,383,61,Smiths Crinkle Cut Chips Chicken,170,2,2.9,MIDAGE SINGLES/COUPLES,Budget,Low Sale,Medium pack
3,2018-08-17,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion,175,5,15.0,MIDAGE SINGLES/COUPLES,Budget,High Sale,Medium pack
4,2018-08-18,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili,150,3,13.8,MIDAGE SINGLES/COUPLES,Budget,High Sale,Small pack
...,...,...,...,...,...,...,...,...,...,...,...,...,...
264828,2019-03-09,272,272319,270088,89,Kettle Sweet Chilli And Sour Cream,175,2,10.8,YOUNG SINGLES/COUPLES,Premium,High Sale,Medium pack
264829,2018-08-13,272,272358,270154,74,Tostitos Splash Of Lime,175,1,4.4,YOUNG SINGLES/COUPLES,Premium,Low Sale,Medium pack
264830,2018-11-06,272,272379,270187,51,Doritos Mexicana,170,2,8.8,YOUNG SINGLES/COUPLES,Premium,High Sale,Medium pack
264831,2018-12-27,272,272379,270188,42,Doritos Corn Chip Mexican Jalapeno,150,2,7.8,YOUNG SINGLES/COUPLES,Premium,High Sale,Small pack
264832,2018-09-22,272,272380,270189,74,Tostitos Splash Of Lime,175,2,8.8,YOUNG SINGLES/COUPLES,Premium,High Sale,Medium pack

## Key Findings Summary

The initial Pandas and NumPy analysis highlighted several important sales and customer behaviour patterns:

- Customer segments show different levels of revenue contribution, with some lifestage and premium customer groups generating higher total sales than others.
- Product revenue and product quantity results show that the highest revenue-generating products are not always the same as the most purchased products by quantity.
- Monthly sales analysis identified the strongest revenue-generating month within the available transaction period.
- High-value customers were identified by grouping transactions by `LYLTY_CARD_NBR` and calculating total customer spend.
- NumPy-based feature engineering was used to create sales and pack-size categories, supporting deeper customer and product segmentation.

These findings provide a strong foundation for the next stage of the project, where SQL will be used for structured business analysis and Power BI will be used for dashboard storytelling.